### ISSUE TITLE
Nothing binds a document to a version: README/AGENTS version claims, seven stale spec stamps, and a `--help` URL pointing at unreleased docs

### ISSUE THREAD

**Issue by CameronBrooks11** [heibench/partspec#300]
## What is wrong — one root cause, three visible instances

The repo has no mechanism connecting any document to the version it describes, and `AGENTS.md:214` declares the opposite: "**Status claims are part of the gate.** The 'Status:' line here and in `README.md` say what does and does not work … Treat them as code: if a change makes one false, the change is not finished."

### Instance 1 — the version claim is unguarded

Two gates already exist and neither covers it: `tests/test_packaging.py:156` pins release.yml's tag-vs-declared-version check, and `tests/test_packaging.py:522` asserts every CHANGELOG heading has a link definition and that `defined["Unreleased"].endswith(f"compare/v{newest}...HEAD")`. But **nothing ties `pyproject.toml:3`'s version to the existence of a `## [<version>]` CHANGELOG heading, and nothing ties `README.md:5` or `AGENTS.md:13` to either.** `grep -rn "0\.7\.6\|0\.7\.5" tests/*.py scripts/*.py` returns only docstring prose about past audits, no assertion. Bump pyproject to 0.7.7 without adding a CHANGELOG section, tag it, and both existing gates pass.

Cutting a release means editing pyproject's version, renaming `[Unreleased]`, adding two link definitions, and rewriting two prose blobs (README `:5-43`, ~412 words; AGENTS `:13-93`, 1,025 words). No CONTRIBUTING, no justfile release recipe, and no doc records that sequence.

### Instance 2 — seven spec Status stamps are stale, and the stamp cannot discriminate versions at all

```
$ git show v0.7.0:docs/SPEC-contract.md | sed -n '1,5p'
$ git show v0.7.6:docs/SPEC-contract.md | sed -n '1,5p'
$ sed -n '1,5p' docs/SPEC-contract.md
```

All three print the identical line: "**Status:** draft 3 · 2026-08-09 · adds §4.8–4.11 (draft_angle, self_intersection_free, step_roundtrip, min_wall) …" — while

```
$ git show v0.7.6:docs/SPEC-contract.md | grep -c '### 4.12'  ->  0
$ grep -n '### 4.12' docs/SPEC-contract.md                    ->  806
```

So the shipped v0.7.6 doc and main's doc carry the same draft number and date while differing by §4.12 (`empty`), §10.1 (`:1068`) and §10.2 (`build_input`).

All seven date pairs drift (stamp date / last content commit): SPEC-contract 08-09/08-21, SPEC-report 08-09/08-21, SPEC-backend 08-09/08-21, SPEC-diff 08-14/08-21, AGENT-CONTRACT 08-08/08-18, LINT 08-09/08-14, FAILURE-MODES 08-08/08-12. The last touches are substantive (SPEC-contract: b0f59fb #257, d4793ba #258, 9d5fa69 #261, 9c29f50 #265). The practice was real and lapsed: `git log -L3,5:docs/SPEC-report.md` shows the status line rewritten on essentially every content commit through 13 drafts up to dfc58ef (2026-08-09), then not once across #241, #244, #262, #264, #265. (Denominator: docs/ holds ten files; `PLAN.md:3` is deliberately "**HISTORICAL.**", and DECISIONS.md and POST-V0.md carry no stamp.)

### Instance 3 — the `--help` URL points at unreleased docs

`src/partspec/cli.py:94-95` prints `https://github.com/CameronBrooks11/partspec/tree/main/docs`, present identically in `git show v0.7.6:src/partspec/cli.py`, so a real PyPI user sees it. `main` is 24 commits past v0.7.6 and its specs normatively define `p.empty()` (§4.12) and `p.build_input()` (§10.2), neither of which exists in 0.7.6 (`git show v0.7.6:src/partspec/contract.py | grep "def empty\|def build_input"` → no match; on main both exist at `contract.py:497` and `:550`). No spec header carries a version applicability line — all four say "draft N · date".

The obvious self-defence fails: `pyproject.toml:3` is `version = "0.7.6"` on main, and `partspec --version` running main prints `partspec 0.7.6`. An agent cross-checking `--version` against the docs is told they match when they do not. And the diagnostic misdirects — a 0.7.6 user who wrote `p.empty()` from §4.12 gets:

```
partspec: the contract raised AttributeError: 'Part' object has no attribute 'empty'
  the contract is wrong, not the part
EXIT=4
```

— which points at rewriting the contract rather than at the install/doc mismatch.

## What NOT to do

The §4 preamble sentence at `SPEC-contract.md:117-124` (which stops at `min_wall` §4.11 and never mentions §4.12) is **narrative provenance, not the vocabulary-closing mechanism**: the generated block at `:141-163` already lists `| p.empty(id=) | empty | none | both |`, is regenerated by `scripts/gen_docs.py`, and is gated by `tests/test_docs.py:659` via `gen-docs --check`. Fix the sentence, but do not treat it as a gate failure.

Also note `tree/v{__version__}/docs` alone is not sufficient as instance-3's fix: because of the static pyproject version, it would send a developer working on main to the stale v0.7.6 docs. The per-spec applicability line is the half that actually holds.

## Smallest fix

1. Two tests in `tests/test_packaging.py`: the newest non-Unreleased CHANGELOG heading equals pyproject's version; `README.md`'s and `AGENTS.md`'s status lines both name that same version.
2. A short release checklist — a comment block at the head of `CHANGELOG.md` or a `just release-check` recipe — naming the five files that must move.
3. One-time bump of the seven Status headers and the §4 preamble sentence. A test asserting each Status date is not older than the newest content commit would over-fire on formatting commits; a pre-commit check that a commit touching `docs/SPEC-*.md` also touches its first ten lines is cheaper and sufficient.
4. Add one line to each spec header giving the first version the document describes and marking sections added since the last tag.

Absorbs the three findings on release narration, stale draft stamps, and the unversioned `--help` docs URL.

Found in the cold-agent legibility and repository-estate audit, 2026-08-22.

**Comment by CameronBrooks11** [comment]
Tracked by #305.
